name: Team Updates
on:

  # manual trigger
  workflow_dispatch:

  # push on main branch
  push:
    branches:
      - main

jobs:
  dispatch-team-management:
    if: github.repository == 'milliondollarideas/team-assignments'
    name: Dispatch Team Management Workflow
    runs-on: ubuntu-latest
    environment: team-management  
    steps:
      # Send the workflow dispatch event via GitHUB API
      - name: dispatch workflow request
        run: |
        curl -L -XPOST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.MDI_ADMIN_ORG_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/milliondollarideas/team-management/dispatches -d '{"event_type":"public_teams_update"}'
