name: Team Aggregate
on:

  # manual trigger
  workflow_dispatch:

  # push on main branch
  push:
    branches:
      - main

jobs:
  dispatch-team-management:
    if: github.repository == 'milliondollarideas/team-assignments'
    name: Run Team override aggregate script
    runs-on: ubuntu-latest
    environment: team-management  
    steps:
      # Checkout repo with full config
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # Run the override aggregate script
      - name: compile aggregate overrides
        run: |
          tools/aggregate_team_overrides.sh ladder/teams ladder/users
