name: Team Updates
on:

  # manual trigger
  workflow_dispatch:

  # push on main branch
  push:
    branches:
      - main

jobs:
  dispatch-team-management:
    if: github.repository == 'milliondollarideas/team-assignments'
    name: Dispatch Team Management Workflow
    runs-on: ubuntu-latest
    environment: team-management  
    steps:
      # Checkout repo with full config
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # Lint team membership files for org members
      - name: check team membership for org membership
        run: tools/lint_members.sh ladder/teams MillionDollarIdeas
      # Run the override aggregate script
      - name: compile aggregate overrides
        env:
          ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
        run: |
          tools/aggregate_team_overrides.sh ladder/teams ladder/users | tee overrides.yaml
      # Send the workflow dispatch event via GitHUB API
      - name: dispatch workflow request
        run: |
          curl -L -XPOST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.MDI_ADMIN_ORG_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/milliondollarideas/team-management/dispatches -d '{"event_type":"public_teams_update"}'
